apiVersion: v1
kind: ReplicationController
metadata:
  name: books
spec:
  replicas: 1
  selector:
    app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: luismoramedina/books-l
          imagePullPolicy: Always
          env:
          - name: SERVER_PORT
            value: "8081"
          - name: STARS_SERVICE_URI
            value: http://stars:8081/stars/{bookId}
          - name: SPRING_APPLICATION_NAME
            value: books
          # linkerd stuff
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: http_proxy
            value: $(NODE_NAME):4140
          # linkerd stuff
---
apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    app: books
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: books
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: stars
spec:
  replicas: 1
  selector:
    app: stars
  template:
    metadata:
      labels:
        app: stars
    spec:
      containers:
        - name: stars
          image: luismoramedina/stars-l
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
            protocol: TCP
          env:
          - name: SPRING_APPLICATION_NAME
            value: stars
          - name: SERVER_PORT
            value: "8081"
          # linkerd stuff
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: http_proxy
            value: $(NODE_NAME):4140
          # linkerd stuff
---
apiVersion: v1
kind: Service
metadata:
  name: stars
  labels:
    app: stars
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: stars
---