version: "3"
services:
  # proxy
  linkerd:
    container_name: linkerd
    image: buoyantio/linkerd:1.3.6
    volumes:
      - ${PWD}/linkerd-conf.yml:/io.buoyant/linkerd/1.3.6/linkerd-conf.yml:ro
      - ${PWD}/disco:/io.buoyant/linkerd/1.3.6/disco:ro
    entrypoint: ./bundle-exec linkerd-conf.yml
    ports:
    - "4140:4140"
    - "9990:9990"
    links:
    - nginx
    - nginx2

  # nginx server
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # nginx server2
  nginx2:
    image: nginx
    container_name: nginx2
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  prometheus:
    image: prom/prometheus:v1.1.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
    command: >
      -config.file=/prometheus/prometheus.yml
      -storage.local.retention=12h
#      -web.console.templates=/usr/share/prometheus/consoles
#      -web.console.libraries=/usr/share/prometheus/console_libraries
    ports:
    - "9090:9090"
    links:
    - linkerd

  grafana:
    image: grafana/grafana:3.1.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    links:
    - prometheus

  zipkin:
    image: openzipkin/zipkin:1.20
    environment:
    - SCRIBE_ENABLED=true
    ports:
      - 9411:9411