version: "3"
services:
  # proxy
  linkerd:
    container_name: linkerd
    image: buoyantio/linkerd:1.3.6
    entrypoint: 
    volumes: 
      - ${PWD}/linkerd-conf.yml:/io.buoyant/linkerd/1.3.6/linkerd-conf.yml
    entrypoint: ./bundle-exec linkerd-conf.yml
    ports:
    - "4140:4140"
    - "9990:9990"
    links:
    - nginx

  # python server
  httpbin:
    image: citizenstig/httpbin
    container_name: httpbin
    ports:
    - "8000:8000"

  # nginx server
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:8080"
    links:
    - httpbin

